name: Ejercicio 2

on: push

jobs:
  ej2:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Bajar código
        uses: actions/checkout@v4
      - name: Analizar calidad
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
